---
- name: grab facts for edge management node
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_edge_management_node": "{{ ec2_name_prefix }}-edge-manager-aws"
  register: edge_management_node_facts

- name: add hosts to groups | edge management node
  add_host:
    name: 'edge-manager-aws'
    username: "{{ student_user }}"
    students: "{{ student_total }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: edge_management,control_nodes
  with_items:
    - "{{ edge_management_node_facts.instances }}"
  changed_when: false
