---

controller_credential_types:
  - name: Kickstart User
    kind: cloud
    inputs:
      fields:
        - id: kickstart_user_username
          type: string
          label: Kickstart User Username
        - id: kickstart_user_password
          type: string
          label: Kickstart User Password
          secret: true
    injectors:
      extra_vars:
        kickstart_user_username: "{  { kickstart_user_username }}"
        kickstart_user_password: "{  { kickstart_user_password }}"
  - name: OSTree Info
    kind: cloud
    inputs:
      fields:
        - id: ostree_repo_protocol
          type: string
          label: OSTree Repo Protocol
        - id: ostree_repo_host
          type: string
          label: OSTree Repo Host
        - id: ostree_repo_port
          type: string
          label: OSTree Repo Port
        - id: ostree_repo_path
          type: string
          label: OSTree Repo Path
        - id: ostree_os_name
          type: string
          label: OSTree OS Name
        - id: ostree_ref
          type: string
          label: OSTree Ref
    injectors:
      extra_vars:
        ostree_repo_protocol: "{  { ostree_repo_protocol }}"
        ostree_repo_host: "{  { ostree_repo_host }}"
        ostree_repo_port: "{  { ostree_repo_port }}"
        ostree_repo_path: "{  { ostree_repo_path }}"
        ostree_os_name: "{  { ostree_os_name }}"
        ostree_ref: "{  { ostree_ref }}"
  - name: Wireless Network Connection Info
    kind: cloud
    inputs:
      fields:
        - id: wifi_network
          type: string
          label: Wireless Network SSID
        - id: wifi_password
          type: string
          label: Wireless Network Password
          secret: true
    injectors:
      extra_vars:
        wifi_network: "{  { wifi_network }}"
        wifi_password: "{  { wifi_password }}"
  - name: Ansible Controller API Authentication Info
    kind: cloud
    inputs:
      fields:
        - id: controller_host
          type: string
          label: Controller Host
        - id: controller_api_username
          type: string
          label: Controller API Username
        - id: controller_api_password
          type: string
          label: Controller API Password
          secret: true
    injectors:
      extra_vars:
        controller_host: "{  { controller_host }}"
        controller_api_username: "{  { controller_api_username }}"
        controller_api_password: "{  { controller_api_password }}"        
