---

controller_credentials:
  - name: Gitea Credentials
    organization: "Student{{ student_number }} Organization"
    credential_type: Source Control
    inputs:
      username: "student{{ student_number }}"
      password: "{{ admin_password }}"
  - name: Edge Manager SSH Credentials
    organization: "Student{{ student_number }} Organization"
    credential_type: Machine
    inputs: "{{ edge_manager_credential_inputs }}"
