---

controller_inventories:
  - name: Edge Systems
    organization: "Student{{ student_number }} Organization"
    variables:
      student_number: "{{ student_number }}"
  - name: Edge Utilities
    organization: "Student{{ student_number }} Organization"
    variables:
      student_number: "{{ student_number }}"
