---

controller_job_templates:
  - name: Test Device Connectivity
    organization: "Student{{ student_number }} Organization"
    inventory: Edge Systems
    project: Device Edge Codebase
    playbook: playbooks/hello-world.yml
    credentials:
      - Device Credentials
