---

- name: create directory for yaml
  ansible.builtin.file:
    path: "{{ pod_dir }}"
    state: directory

- name: flow if state == present
  when:
    - state is not defined or
      (state is defined and state != 'absent')
  block:
    - name: create volumes
      ansible.builtin.include_tasks:
        file: volumes.yml
      when:
        - pod.spec.volumes is defined

    - name: run pod
      ansible.builtin.include_tasks:
        file: run-pod.yml

- name: flow if state == absent
  when:
    - state is defined
    - state == 'absent'
  block:
    - name: stop the pods
      ansible.builtin.include_tasks:
        file: run-pod.yml 
    - name: create volumes
      ansible.builtin.include_tasks:
        file: volumes.yml
      when:
        - pod.spec.volumes is defined


  