---

- name: push out pod {{ pod.name }} yaml
  ansible.builtin.copy:
    content: "{{ pod.definition }}"
    dest: "{{ pod_dir }}/{{ pod.name }}.yml"
    owner: "{{ ansible_user }}"

- name: override state for 'absent'
  ansible.builtin.set_fact:
    pod_state: absent
    play_pod_state: absent
  when:
    - state is defined
    - state == 'absent'

- name: play yaml to create pod {{ pod.name }}
  containers.podman.podman_play:
    kube_file: "{{ pod_dir }}/{{ pod.name }}.yml"
    state: "{{ play_pod_state }}"
