---

- name: ensure podman is present
  ansible.builtin.dnf:
    name: podman
  become: true

- name: ensure parent {{ build_dir }} exists
  ansible.builtin.file:
    path: "{{ build_dir }}"
    state: directory

- name: create parent {{ source_control_tmp_dir }} exists
  ansible.builtin.file:
    path: "{{ source_control_tmp_dir }}"
    state: directory

- name: enable lingering for {{ ansible_user }}
  ansible.builtin.shell:
    cmd: loginctl enable-linger {{ ansible_user }}
  args:
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"
  become: true

- name: set git config options for push
  block:
    - name: set git user.name
      ansible.builtin.shell:
        cmd: git config --global user.name "Workshop Provisioner"
      changed_when: false
    - name: set git user.email
      ansible.builtin.shell:
        cmd: git config --global user.email "dont@email.me"
      changed_when: false
