---
theme: jekyll-theme-dinky
include:
  - "provisioner/README.md"
exclude:
  - "roles"
  - "provisioner/roles"
  - "provisioner/group_vars"
  - "provisioner/inventory"
  - "provisioner/tests"
  - "legacy-assets"
  - "exercises/rhde_aw_120/2.1-kickstart-template/README.md"
kramdown:
  syntax_highlighter_opts:
    disable: true
