---

- name: load in {{ workshop_type }} vars
  ansible.builtin.include_vars:
    file: "vars/{{ workshop_type }}/controller-config.yml"

- name: import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: include cross-organization config
  ansible.builtin.include_tasks:
    file: cross-organization.yml

- name: include organization-specific config
  ansible.builtin.include_tasks:
    file: organization-specific.yml

- name: include tasks to configure controller | user level
  ansible.builtin.include_tasks:
    file: user-specific.yml
  vars:
    controller_username: "student{{ student_number }}"
  loop: "{{ (range(1, (student_total + 1), 1)|list) }}"
  loop_control:
    loop_var: student_number
