---

- name: aws specific vars
  when:
    - "'aws' in group_names"
  block:
    - name: set ssh key path
      ansible.builtin.set_fact:
        ssh_key_path: "{{ playbook_dir }}/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}/ssh-key.pem"
    - name: set vars for aws controller
      ansible.builtin.set_fact:
        edge_manager_host: "{{ route53_domains.controller.domain }}"
        edge_manager_credential_inputs:
          username: "{{ ansible_user }}"
          ssh_key_data: "{{ lookup('file', ssh_key_path) }}"
        source_control_hostname: "{{ route53_domains.gitea.domain }}"

- name: local specific vars
  when:
    - "'local' in group_names"
  block:
    - name: set vars for local controller
      ansible.builtin.set_fact:
        edge_manager_host: "{{ ansible_host }}"
        edge_manager_credential_inputs:
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          become_password: "{{ ansible_become_password }}"        
        source_control_hostname: "{{ ansible_host }}"
