---

- name: aws specific vars
  when:
    - "'aws' in group_names"
  block:
    - name: set path to ec2 instance ssh key
      ansible.builtin.set_fact:
        ssh_key_data_path: "{{ playbook_dir }}/{{ ec2_name_prefix }}/{{ ec2_name_prefix }}-private.pem"
    - name: set vars for aws controller
      ansible.builtin.set_fact:
        edge_manager_host: "{{ route53_domains.controller.domain }}"
        source_control_hostname: "{{ route53_domains.gitea.domain }}"

- name: local specific vars
  when:
    - "'local' in group_names"
  block:
    - name: set vars for local controller
      ansible.builtin.set_fact:
        edge_manager_host: "{{ ansible_host }}"
        source_control_hostname: "{{ ansible_host }}"
