---

- name: download undionly
  ansible.builtin.get_url:
    url: http://boot.ipxe.org/undionly.kpxe
    dest: "{{ build_dir }}/tftp/undionly.kpxe"
  register: download_undionly
  until: download_undionly is not failed
  retries: 15
  delay: 20
