---

collections:
  - name: ansible.utils
  - name: ansible.posix
  - name: awx.awx
  - name: community.aws
  - name: community.crypto
  - name: community.general
  - name: community.mysql
  - name: containers.podman
  - name: redhat_cop.controller_configuration
  - name: fedora.linux_system_roles
  - git+https://github.com/ansible-collections/osbuild.composer