---

- name: enable baseos/appstream
  community.general.rhsm_repository:
    name:
      - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms"
      - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms"
    state: enabled
  when:
    - use_rhsm_repos|bool
