---

- name: import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: loop through student blueprints
  ansible.builtin.include_tasks:
    file: blueprints.yml
  loop: "{{ (range(1, (student_total + 1), 1)|list) }}"
  loop_control:
    loop_var: student_number

- name: push generic blueprint
  ansible.builtin.import_tasks: generic-blueprint.yml

- name: compose installer image
  ansible.builtin.import_tasks: compose-installer.yml

- name: link into student directories
  ansible.builtin.include_tasks:
    file: student-composes.yml
  loop: "{{ (range(1, (student_total + 1), 1)|list) }}"
  loop_control:
    loop_var: student_number
