---
- name: Teardown attendance
  include_tasks: teardown.yml
  when: teardown|bool

- name: setup attendance instance
  block:
    - name: setup DNS specific information
      include_tasks: "{{ item }}"
      with_first_found:
        - "{{role_path}}/tasks/{{ dns_type }}.yml"
        - "{{role_path}}/tasks/none.yml"

    - name: install package dependencies for attendance instance
      include_tasks: 10_package_dependencies.yml

    - name: attempt to get SSL certificates
      when:
        - use_zerossl is not defined or
          not use_zerossl|bool
      block:
        - name: retrieve SSL cert with certbot
          include_tasks: 20_certbot.yml
      rescue:
        - name: append dns_information failure
          set_fact:
            dns_information:
              - "{{ dns_information }}"
              - "The Lets Encrypt certbot failed for the attendance node, please check https://letsencrypt.status.io/ to make sure the service is running"

        - name: error with SSL cert
          debug:
            msg: "Unable to retrieve SSL cert, ERROR, continuing on with self-signed cert..."

    - name: attempt to get SSL certificates | zeroSSL
      when:
        - use_zerossl is defined
        - use_zerossl|bool
      block:
        - name: use zerossl_cert role
          ansible.builtin.include_role:
            name: "{{ role_path }}/../zerossl_cert"
          vars:
            domain_name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
            _cert_owner: nginx
            _cert_group: nginx
      rescue:
        - name: error with SSL cert
          debug:
            msg: "Unable to retrieve SSL cert, ERROR, continuing on with self-signed cert..."

    - name: install and configure nginx on attendance node
      include_tasks: 30_nginx.yml

    - name: Configure attendance host
      import_tasks: 40_attendance.yml
  when: not teardown
