---

- name: install common packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"

- name: ensure dnsmasq isn't installed locally
  ansible.builtin.dnf:
    name: dnsmasq
    state: absent
