---
- name: make sure .ssh is created
  file:
    path: "/home/{{ ansible_user }}/.ssh/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Apply patch for runner fix PR759
  lineinfile:
    path: /usr/lib/python3.8/site-packages/ansible_runner/config/_base.py
    regexp: ".*--userns=keep-id.*"
    state: absent

##
# @todo @craig-br This needs immprovement. Multiple ssh-agent instances
# are running for each bash session
##
- name: add custom bashrc for student
  template:
    src: bashrc.j2
    dest: /home/{{ ansible_user }}/.bashrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

# Login into Red Hat registry
- name: Login to redhat registry
  containers.podman.podman_login:
    username: '{{ redhat_username }}'
    password: '{{ redhat_password }}'
    registry: '{{ ee_registry_name }}'
  become_user: "{{ ansible_user }}"
  register: login_registry
  until: login_registry is not failed
  retries: 5

- name: copy over ssh config file for student
  template:
    src: sshconfig.j2
    dest: /home/{{ ansible_user }}/.ssh/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
