---

- name: setup gitea
  hosts:
    - edge_management
  pre_tasks:
    - name: set source_control_host dns name and setup record
      when:
        - route53_domains.gitea is defined
      block:
        - name: set var for gitea role
          ansible.builtin.set_fact:
            source_control_hostname: "{{ route53_domains.gitea.domain }}"
        - name: setup dns in route53
          ansible.builtin.include_role:
            name: ../roles/aws_dns
          vars:
            route53_dns_record: "{{ route53_domains.gitea.domain }}"
    
    - name: fallback to ip address
      ansible.builtin.set_fact:
        source_control_hostname: "{{ ansible_host }}"
      when:
        - source_control_hostname is not defined
  tasks:
    - name: include gitea setup role
      ansible.builtin.include_role:
        name: ../roles/setup_gitea
