---

- name: populate controller for students
  hosts:
    - edge_management
  gather_facts: false
  connection: local
  pre_tasks:
    - name: enforce var
      ansible.builtin.set_fact:
        controller_configuration_projects_async_retries: 300
  tasks:
    - name: populate controller
      ansible.builtin.include_role:
        name: ../roles/populate_single_controller
