---

- name: populate controller for students
  hosts:
    - edge_management
  tasks:
    - name: populate controller
      ansible.builtin.include_role:
        name: ../roles/populate_single_controller
