---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: workshop collection final check
      block:
        - name: run pre-check role to make sure workshop will complete provisioning
          include_role:
            name: ../roles/workshop_check_setup

        - name: run AWS check setup if using AWS
          include_role:
            name: ../roles/aws_check_setup

        - name: download AAP
          include_role:
            name: ../roles/aap_download
          when: not pre_build | bool

      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.
