---

- name: reset local services completely
  hosts:
    - 'edge_management:&local'
  pre_tasks:
    - name: attempt to load in vars for workshop
      ansible.builtin.include_vars:
        file: "workshop_vars/{{ workshop_type }}.yml"
  tasks:
    - name: loop over pods
      ansible.builtin.include_role:
        name: ../roles/run_local_services
        apply:
          become: "{{ pod.privileged | default(false) }}"
          vars:
            state: absent
      loop: "{{ pods }}"
      loop_control:
        loop_var: pod
    - name: dump the images
      containers.podman.podman_image:
        name: "localhost/{{ image.name }}:latest"
        state: absent
      loop: "{{ local_services }}"
      loop_control:
        loop_var: image