---

- name: issue wildcard cert
  hosts:
    - 'edge_management:&local'
  tasks:
    - name: get wildcard cert if possible
      when:
        - dns_type == 'aws'
        - workshop_type == 'rhde_tse'
      block:
        - name: make a directory for cert storage
          ansible.builtin.file:
            path: "{{ directory }}"
            state: directory
          loop:
            - "~/workshop-certs"
            - "~/workshop-certs/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
          loop_control:
            loop_var: directory
        - name: issue base domain cert
          ansible.builtin.include_role:
            name: ../roles/zerossl_cert
          vars:
            domain_name: "{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
            _cert_dir: "~/workshop-certs/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
            _cert_owner: "{{ ansible_user }}"
            _cert_group: "{{ ansible_user }}"
            wildcard: true
