---

- name: validate vars are defined for selected workshop
  hosts:
    - edge_management
  gather_facts: false
  pre_tasks:
    - name: load in workshop vars
      ansible.builtin.include_vars:
        file: "workshop_vars/{{ workshop_type }}.yml"
  tasks:
    - name: validate common vars
      ansible.builtin.assert:
        that:
          - student_total is defined
          - redhat_username is defined
          - redhat_password is defined
          - base_zone is defined
          - sub_domain is defined
          - zerossl_account is defined
          - base64_manifest is defined
          - offline_token is defined
          - admin_password is defined
          - external_connection is defined
          - internal_connection is defined
        fail_msg: |
          Ensure necessary vars are set.
          For example extra-vars files, check the provisioner/example-extra-vars directory.
    - name: check env vars for AWS
      block:
        - name: test for AWS_ACCESS_KEY_ID
          ansible.builtin.fail:
            msg: AWS_ACCESS_KEY_ID is not defined
          when:
            - lookup('env', "AWS_ACCESS_KEY_ID") | length <= 0
        - name: test for AWS_SECRET_ACCESS_KEY
          ansible.builtin.debug:
            msg: AWS_SECRET_ACCESS_KEY is not defined
          when:
            - lookup('env', "AWS_SECRET_ACCESS_KEY") | length <= 0
      rescue:
        - name: fail out on undefined aws vars
          ansible.builtin.fail:
            msg: "Ensure AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are exported to your shell session."
